FROM node:18.18.0-alpine as build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm i
COPY . .
# RUN npm run build
RUN npm ci --silent


FROM nginx:stable-alpine
EXPOSE 3000
COPY   ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html




